services:
  web-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db_mysql
    environment: 
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/demo_docker_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
  db_mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_docker_db
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: